web:
  static_path:
  port: 9990
application:
  log:
    level: debug
    logPath: ./asset/log/log.log
gorm:
  debug: true
  driverName: mysql
  max_lifetime: 72000
  max_open_conns: 150
  max_idle_conns: 100
  mysql:
    host: 124.222.147.194
    port: 3306
    username: root
    password: root
    database: globalization_language_document
    charset: utf8
    loc: Asia/Shanghai
    parameters: parseTime=True&%2FShanghai